project_id = "rskzizedzagohmvyhuyu"

[functions.enhance-post]
verify_jwt = false

[functions.enhance-profile]
verify_jwt = true

[functions.analyze-virality]
verify_jwt = false

[functions.handle-payment]
verify_jwt = false

[functions.handle-credits]
verify_jwt = true

[functions.handle-razorpay-payment]
verify_jwt = false

[cron]
# Add a cron job to check for scheduled shares every minute
schedule_share = "* * * * *"

